import React from 'react';
import ReactMarkdown from 'react-markdown';
import { BsXLg, BsRobot } from 'react-icons/bs';
import { useTheme } from '../../providers/ThemeProvider';

interface HealthReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  reportMarkdown: string | null;
}

export default function HealthReportModal({ isOpen, onClose, reportMarkdown }: HealthReportModalProps) {
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 animate-in fade-in duration-200">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal Container */}
      <div className={`relative w-full max-w-4xl max-h-[90vh] flex flex-col rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200 ${
        isDark ? 'bg-[#111111] border border-white/10' : 'bg-white border border-gray-200'
      }`}>
        
        {/* Header */}
        <div className={`flex-shrink-0 flex items-center justify-between p-5 border-b sticky top-0 z-10 ${
          isDark ? 'bg-[#111111]/90 border-white/10' : 'bg-white/90 border-gray-200'
        } backdrop-blur-md`}>
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg ${isDark ? 'bg-purple-500/20 text-purple-400' : 'bg-purple-100 text-purple-600'}`}>
              <BsRobot className="w-5 h-5" />
            </div>
            <div>
              <h2 className={`text-lg font-bold tracking-tight ${isDark ? 'text-white' : 'text-gray-900'}`}>
                AI System Health Analysis
              </h2>
              <p className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
                Generated by Llama 3.1 8B via Groq
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className={`p-2 rounded-xl transition-colors ${
              isDark ? 'hover:bg-white/10 text-gray-400 hover:text-white' : 'hover:bg-gray-100 text-gray-500 hover:text-gray-900'
            }`}
          >
            <BsXLg className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 lg:p-10 custom-scrollbar scroll-smooth">
          {reportMarkdown ? (
            <div className={`markdown-content space-y-4 ${
              isDark ? 'text-gray-300' : 'text-gray-700'
            }`}>
              <ReactMarkdown
                components={{
                  h1: ({node, ...props}) => <h1 className={`text-2xl font-bold mb-4 mt-6 ${isDark ? 'text-white' : 'text-black'}`} {...props} />,
                  h2: ({node, ...props}) => <h2 className={`text-xl font-bold mb-3 mt-6 border-b pb-2 ${isDark ? 'text-white border-white/10' : 'text-black border-gray-200'}`} {...props} />,
                  h3: ({node, ...props}) => <h3 className={`text-lg font-bold mb-2 mt-4 ${isDark ? 'text-white' : 'text-black'}`} {...props} />,
                  p: ({node, ...props}) => <p className="mb-4 leading-relaxed" {...props} />,
                  ul: ({node, ...props}) => <ul className="list-disc pl-6 mb-4 space-y-2" {...props} />,
                  ol: ({node, ...props}) => <ol className="list-decimal pl-6 mb-4 space-y-2" {...props} />,
                  li: ({node, ...props}) => <li className="leading-relaxed" {...props} />,
                  strong: ({node, ...props}) => <strong className={`font-bold ${isDark ? 'text-white' : 'text-black'}`} {...props} />,
                  blockquote: ({node, ...props}) => <blockquote className={`pl-4 border-l-4 italic my-4 ${isDark ? 'border-purple-500 bg-purple-500/10 text-gray-300' : 'border-purple-500 bg-purple-50 tracking-tight text-gray-700'} p-3 rounded-r-lg`} {...props} />,
                }}
              >
                {reportMarkdown}
              </ReactMarkdown>
            </div>
          ) : (
             <div className="flex flex-col items-center justify-center py-20 text-center opacity-60 relative h-full">
               <div className="absolute inset-0 bg-gradient-to-b from-transparent to-[#111111]/10 pointer-events-none" />
               <BsRobot className="w-16 h-16 mb-4 text-gray-400 animate-pulse" />
               <p className="text-lg">No report data generated yet.</p>
             </div>
          )}
        </div>
      </div>
    </div>
  );
}
